PSA NUTS-LSP.md
minvws/generiekefuncties-beproevingen pull request #1
Opened 2024-04-03 07:10 UTC by PieterVanGemeren

# PSA PoC NUTS-LSP
[beproeving medicatieoverdracht VVT-1e lijn (NUTS-LSP)]

Dit document dient: 

- als praatstuk om ervoor te zorgen dat we in gezamenlijkheid de beste oplossing kunnen vaststellen en om te borgen dat de verschillende stakeholders allen dezelfde stip op de horizon voor ogen krijgen. 

- om te bepalen welke GAPS dan wel OVERLAPS er tussen huidige situatie en gewenste/toekomstige situatie zijn om te kunnen bepalen welke acties er nodig zijn om in lijn met de doelstellingen voor eind 2025 te komen.

2024-04-12 12:53 UTC, stevenvegt requested changes
Dingetjes.

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +3.	Enrollment wijzedat gebruikt kan worden voor de uitrol van  attributen in wallets  .
wijzedat -> wijze, dat

Wat is een Enrollment wijze?

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +2.	Een herbruikbare open source GtK referentie-implementatie
🎉

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +4.	Afspraken over gebruik taakcodes  (naast rolcode) voor taak: toediener (VVT). Taakcodes zijn essentieel voor de VVT sector, omdat er veel zorgprofessionals werken die niet kunnen worden gekwalific
Is het realistisch om te afspraken als resultaat te zien, of doen we vooral ervaringen op? Afspraken vergt het opzetten van een hele governance rondom het uitgeven van deze credentials etc. en dat is misschien buiten scope van de dit project?

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +Drie wallet apps. Twee  zorgverlener wallets en een zorgaanbieder XIS-wallet (Hiermee kunnen we  aantonen dat het niet uitmaakt welke wallet app een ZV kiest. Het gaat hierbij om het idee dat  meerde
XIS wallet wordt ook wel een wallet-agent genoemd.

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +b.	Die dossierhouders in staat stellen gegevens vrij te geven obv een OAuth/OIDC VC service die accestokens kan uitgeven op basis van landelijke autorisatieafspraak waarbinnen een dossierhouder gegev
Zie ook eerdere opmerking, waarom die RBAC niet (ook) bij de bronhouder afdwingen? En even naar die standaarden kijken, ik denk dat je OpenID4VP bedoelt? https://openid.net/specs/openid-4-verifiable-presentations-1_0.html

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +Een Toestemmingsvoorziening (TV) met een PDP (policy decision point) waar  toestemmingen kunnen worden gechecked: We gebruiken hiervoor de gesloten autorisatievraag van Mitz
k weet nog niet of we de PDP bij de OTV willen zetten of bij het knooppunt. Ik zou voor het laatste gaan en de OTV alleen de toestemmingsvoorkeuren laten beheren. Dit ligt volgens mij ook meer in lijn met wat de werkgroepen GF toestemmingen en de NEN aan het bedenken zijn.

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +Zowel NUTS als het Landelijk Schakelpunt (LSP) vereisen onweerlegbaarheid bij de uitwisseling van medische gegevens. Hiervoor worden verifieerbare verklaringen (SAML tokens bij LSP, VC’s bij NUTS), m
Technisch gezien gebruikt Nuts Verifiable Presentations met daarin Verifiable credentials. VP(VCs). Ik denk dat SAML tokens ook bestaat uit SAML assertions?

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +## Samenhang/afhankelijkheden met andere trajecten
MP9? Generieke Functies en LDN?

2024-04-12 12:53 UTC, stevenvegt commented on PoC's/NUTS-LSP/PSA.md
> +In de huidige situatie kunnen geen medicatiegegevens worden opgevraagd/uitgewisseld tussen VVT-instellingen, huisartsen en apothekers. Dit komt omdat de vertrouwensmodellen van de onderliggende “infr
kenlpunt -> kneppunt

2024-06-05 13:20 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Tijdlijnen behoren niet in een PSA. We kiezen voor een agile aanpak. Beginnen met stubs/drivers die we langzaam gaan vervangen voor werkelijke functionaliteit zodat het een lerende uitrol wordt. Per
verwerkt

2024-06-05 13:22 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +- VWS
toegevoegd

2024-06-05 13:31 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Er is in een Proof of Concept omgeving met een koppeling tussen een aantal stub NUTS nodes (vertegenwoordigd per node één VVT-instelling) die medicatiegegevens kan uitwisselen met op de LSP-testomgev
We waren opzoek naar een term om het concept achter een standaard als VC's of SAML-assetions te duiden. Het gaat om cryptografisch onweerlegbare statements, bv een signed token met daarin de identiteit van een zorgaanbieder. Ik heb het begrip nav je feedback geintroduceerd in begrippenlijst als: een  claim/statement of (meta)data die middels cryptografische technieken onweerlegbaar is gemaakt, waarvan cryptografisch te bewijzen is wie deze heeft uitgegeven en waarvan de integriteit cryptografisch is gewaarborgd.

2024-06-05 13:40 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +## Lijst met aannamen
Genoemd als aanname 0

2024-06-05 13:44 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Alternatief: We gaan ervan uit dat voor het vullen en beschikbaarstellen van identificatie attributen in een wallet het OpenID4VC protolcol wordt gebruiky. Dez aanname loopt vooruit op de nog vrij te
verwerkt

2024-06-05 13:53 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +We gaan er vanuit dat de dossierhouder op raadplegende zorgaanbieder type autoriseert en de raadpleger de RBAC verantwoordelijkheid krijgt gebaseerd op een in de nieuwe governance vastgestelde pas-to
Volgens mij zijn we het hier met elkaar eens maar is het ongelukkig opgeschreven. Ik heb het nu als volgt opgeschreven: We gaan er vanuit dat de dossierhouder op raadplegende zorgaanbiedertype autoriseert en verantwoordelijk is voor Attribute-based access control (ABAC) waarvoor de hard af te dwingen regels/policies in de nieuwe governance zijn vastgesteld en dat de raadpleger de Role Based Access Control (RBAC) verantwoordelijkheid krijgt gebaseerd op een in de nieuwe governance vastgestelde 'pas-toe-of-leg-uit' autorisatieregels. Deze regels zijn dus minder hard omdat er aan de raadplegende kant van kan worden afgeweken op een voor een auditor uitlegbare manier.

2024-06-05 13:55 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +3.	Enrollment wijzedat gebruikt kan worden voor de uitrol van  attributen in wallets  .
Entrollment van attributen in wallets. Hoe doe je dat op het juiste betrouwbaarheidsniveau. Heb ervan gemaakt: Enrollment proces dat gebruikt kan worden voor de uitrol van  attributen in wallets op het juiste betrouwbaarheidsniveau.

2024-06-05 16:33 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +4.	Afspraken over gebruik taakcodes  (naast rolcode) voor taak: toediener (VVT). Taakcodes zijn essentieel voor de VVT sector, omdat er veel zorgprofessionals werken die niet kunnen worden gekwalific
Heb er conceptafspraken van gemaakt:
4.	Conceptafspraken over gebruik taakcodes  (naast rolcode) voor taak: toediener (VVT). Taakcodes zijn essentieel voor de VVT sector, omdat er veel zorgprofessionals werken die niet kunnen worden gekwalificeerd door het CIBG (want geen diploma of opname in register). Uitgangspunt is dat de koepels met een autorisatierichtlijn komen. Contact met programma MO om te kijken of de conceptafspraken die we maken op basis van de opgedane ervaring kunnen laten landen in de MO governance.

2024-06-05 16:35 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Drie wallet apps. Twee  zorgverlener wallets en een zorgaanbieder XIS-wallet (Hiermee kunnen we  aantonen dat het niet uitmaakt welke wallet app een ZV kiest. Het gaat hierbij om het idee dat  meerde
toegevoegd

2024-06-05 16:37 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +b.	Die dossierhouders in staat stellen gegevens vrij te geven obv een OAuth/OIDC VC service die accestokens kan uitgeven op basis van landelijke autorisatieafspraak waarbinnen een dossierhouder gegev
zin bij punt 2b aangepast

2024-06-05 16:44 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Een Toestemmingsvoorziening (TV) met een PDP (policy decision point) waar  toestemmingen kunnen worden gechecked: We gebruiken hiervoor de gesloten autorisatievraag van Mitz
Aangepast naar:
Een Toestemmingsvoorziening (TV) met een PDP (policy decision point) in de OTV danwel in het knooppunt waar toestemmingen kunnen worden gechecked: We gebruiken hiervoor de gesloten autorisatievraag van Mitz

2024-06-05 16:46 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +## Samenhang/afhankelijkheden met andere trajecten
toegevoegd

2024-06-05 16:47 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +Zowel NUTS als het Landelijk Schakelpunt (LSP) vereisen onweerlegbaarheid bij de uitwisseling van medische gegevens. Hiervoor worden verifieerbare verklaringen (SAML tokens bij LSP, VC’s bij NUTS), m
Aangepast

2024-06-05 16:48 UTC, PieterVanGemeren commented on PoC's/NUTS-LSP/PSA.md
> +In de huidige situatie kunnen geen medicatiegegevens worden opgevraagd/uitgewisseld tussen VVT-instellingen, huisartsen en apothekers. Dit komt omdat de vertrouwensmodellen van de onderliggende “infr
aangepast

2024-06-05 17:35 UTC, PieterVanGemeren reviewed
Alle feedback verwerkt

2024-06-12 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/minvws/generiekefuncties-beproevingen?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/minvws/generiekefuncties-beproevingen?pullRequest=1) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: PieterVanGemeren<br/>:x: RonObbens<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/minvws/generiekefuncties-beproevingen?pullRequest=1) it.</sub>

2024-07-05 06:55 UTC, RonObbens commented
Vraag over autorisatie behandeld, fictieve rolcode hanteren tijdens de PoC omdat er nog aan rolcodes wordt gewerkt voor niet BIG-ers.

2024-07-05 07:00 UTC, RonObbens approved these changes

2024-07-05 07:00 UTC, PieterVanGemeren commented
> Dingetjes.

done

2024-07-05 07:03 UTC, merged